### ISSUE TITLE
requirements中没有streamlit，直接运行示例程序会报错

### ISSUE THREAD

**Issue by Halflifefa** [shibing624/agentica#4]
### Describe the bug
直接运行streamlit run llm_os_demo.py会提示没有streamlit

按照llm_os_demo.py中的提示安装完额外所需依赖后再运行, 报如下错误
```
Traceback (most recent call last):
  File "/miniconda3/lib/python3.12/site-packages/agentica/emb/text2vec_emb.py", line 9, in <module>
    from text2vec import SentenceModel
  File "/miniconda3/lib/python3.12/site-packages/text2vec/__init__.py", line 8, in <module>
    from text2vec.bertmatching_model import BertMatchModel
  File "/miniconda3/lib/python3.12/site-packages/text2vec/bertmatching_model.py", line 11, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/miniconda3/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "/agentica/examples/llm_os_demo.py", line 22, in <module>
    from agentica.emb.text2vec_emb import Text2VecEmb
  File "/miniconda3/lib/python3.12/site-packages/agentica/emb/text2vec_emb.py", line 11, in <module>
    raise ImportError(
ImportError: `text2vec` not installed. Please install it with `pip install text2vec`
2024-07-04 09:23:40.786 Uncaught app exception
Traceback (most recent call last):
  File "/miniconda3/lib/python3.12/site-packages/agentica/emb/text2vec_emb.py", line 9, in <module>
    from text2vec import SentenceModel
  File "/miniconda3/lib/python3.12/site-packages/text2vec/__init__.py", line 8, in <module>
    from text2vec.bertmatching_model import BertMatchModel
  File "/miniconda3/lib/python3.12/site-packages/text2vec/bertmatching_model.py", line 11, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/miniconda3/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "/agentica/examples/llm_os_demo.py", line 22, in <module>
    from agentica.emb.text2vec_emb import Text2VecEmb
  File "/miniconda3/lib/python3.12/site-packages/agentica/emb/text2vec_emb.py", line 11, in <module>
    raise ImportError(
ImportError: `text2vec` not installed. Please install it with `pip install text2vec`

```

### To Reproduce
```
git clone https://github.com/shibing624/agentica.git
cd agentica
pip install .
cd examples
pip install streamlit agentica text2vec sqlalchemy lancedb pyarrow yfinance
streamlit run llm_os_demo.py
```
### Describe your attempts
- [ √ ] I checked the documentation and found no answer
- [ √ ] I checked to make sure that this is not a duplicate issue

You should also provide code snippets you tried as a workaround, StackOverflow solution that you have walked through, or your best guess of the cause that you can't locate (e.g. cosmic radiation).

### Context
 - **OS** [e.g. Windows 10, macOS 10.14]: Ubuntu 22.04.4 LTS
 - **Hardware** [e.g. CPU only, GTX 1080 Ti]: RTX 4090

### Additional Information
Other things you want the developers to know.

**Comment by shibing624** [comment]
<img width="889" alt="image" src="https://github.com/shibing624/agentica/assets/10249622/6c4b8d17-bc34-475a-8c86-367ad1425230">

**Comment by shibing624** [comment]
pip install torch
